sudo: false
dist: xenial
language: php

services:
  - mysql

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1

before_script:
  - git clone --depth=50 --branch=2020.07 git://github.com/aimeos/aimeos-core.git ../aimeos-core
  - git clone --depth=50 --branch=2020.07 git://github.com/aimeos/ai-controller-frontend ../aimeos-core/ext/ai-controller-frontend
  - cd ../aimeos-core && mv ../ai-client-jsonapi ext/
  - travis_retry composer require "nyholm/psr7-server:^0.4.1"
  - mysql -e "CREATE DATABASE aimeos; GRANT ALL ON aimeos.* TO 'aimeos'@'127.0.0.1' IDENTIFIED BY 'aimeos'"
  - echo "<?php return array( 'db' => array( 'adapter' => 'mysql', 'host' => '127.0.0.1', 'database' => 'aimeos', 'username' => 'aimeos', 'password' => 'aimeos', 'limit' => 2, 'opt-persistent' => false, 'stmt' => array( \"SET SESSIOn sort_buffer_size=2097144; SET NAMES 'utf8'; SET SESSION sql_mode='ANSI'\" ) ), 'mq' => array( 'adapter' => 'Standard', 'db' => 'db' ) );" > config/resource.php

script:
  - vendor/bin/phing -Ddir=ext/ai-client-jsonapi setup coverageext checkext

after_success:
  - php vendor/bin/coveralls -c ext/ai-client-jsonapi/.coveralls.yml

matrix:
  fast_finish: true
  include:
    - language: node_js
      node_js: 12
      before_script:
        - npm install --save-dev ava axios @babel/core @babel/preset-env @babel/register
      script:
        - npm test
    - language: node_js
      node_js: 10
      before_script:
        - npm install --save-dev ava axios @babel/core @babel/preset-env @babel/register
      script:
        - npm test
    - language: node_js
      node_js: 8
      before_script:
        - npm install --save-dev ava axios @babel/core @babel/preset-env @babel/register
      script:
        - npm test
